// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'lexer.dart';

// **************************************************************************
// TableDrivenScannerGenerator
// **************************************************************************

const _$defaultContextScanner = BuiltScanner<TokenType>([
  DState([
    Transition(40, 40, 1),
    Transition(41, 41, 2),
    Transition(42, 42, 3),
    Transition(43, 43, 4),
    Transition(46, 46, 5),
    Transition(63, 63, 6),
    Transition(91, 91, 7),
    Transition(92, 92, 8),
    Transition(93, 93, 9),
    Transition(124, 124, 10),
  ], defaultTransition: 11),
  DState([], defaultTransition: -1, accept: groupStart),
  DState([], defaultTransition: -1, accept: groupEnd),
  DState([], defaultTransition: -1, accept: repetitionStar),
  DState([], defaultTransition: -1, accept: repetitionPlus),
  DState([], defaultTransition: -1, accept: dot),
  DState([], defaultTransition: -1, accept: repetitionQuestionmark),
  DState([], defaultTransition: -1, accept: characterSetStart),
  DState([
    Transition(40, 40, 12),
    Transition(41, 41, 13),
    Transition(42, 42, 14),
    Transition(43, 43, 15),
    Transition(46, 46, 16),
    Transition(48, 48, 17),
    Transition(63, 63, 18),
    Transition(91, 91, 19),
    Transition(92, 92, 20),
    Transition(93, 93, 21),
    Transition(102, 102, 22),
    Transition(110, 110, 23),
    Transition(114, 114, 24),
    Transition(116, 116, 25),
    Transition(117, 117, 26),
    Transition(118, 118, 27),
    Transition(124, 124, 28),
  ], defaultTransition: -1, accept: _unrecognizedEscape),
  DState([], defaultTransition: -1, accept: characterSetEnd),
  DState([], defaultTransition: -1, accept: choice),
  DState([], defaultTransition: -1, accept: literal),
  DState([], defaultTransition: -1, accept: _defaultContextEscapes),
  DState([], defaultTransition: -1, accept: _defaultContextEscapes),
  DState([], defaultTransition: -1, accept: _defaultContextEscapes),
  DState([], defaultTransition: -1, accept: _defaultContextEscapes),
  DState([], defaultTransition: -1, accept: _defaultContextEscapes),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([], defaultTransition: -1, accept: _defaultContextEscapes),
  DState([], defaultTransition: -1, accept: _sharedContextEscapes),
  DState([], defaultTransition: -1, accept: _sharedContextEscapes),
  DState([], defaultTransition: -1, accept: _sharedContextEscapes),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([
    Transition(123, 123, 29),
  ], defaultTransition: -1),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([], defaultTransition: -1, accept: _defaultContextEscapes),
  DState([
    Transition(48, 57, 30),
    Transition(65, 70, 31),
    Transition(97, 102, 32),
  ], defaultTransition: -1),
  DState([
    Transition(48, 57, 30),
    Transition(65, 70, 31),
    Transition(97, 102, 32),
    Transition(125, 125, 33),
  ], defaultTransition: -1),
  DState([
    Transition(48, 57, 30),
    Transition(65, 70, 31),
    Transition(97, 102, 32),
    Transition(125, 125, 33),
  ], defaultTransition: -1),
  DState([
    Transition(48, 57, 30),
    Transition(65, 70, 31),
    Transition(97, 102, 32),
    Transition(125, 125, 33),
  ], defaultTransition: -1),
  DState([], defaultTransition: -1, accept: _unicodeEscape),
]);

const _$characterSetScanner = BuiltScanner<TokenType>([
  DState([
    Transition(45, 45, 1),
    Transition(91, 91, 2),
    Transition(92, 92, 3),
    Transition(93, 93, 4),
    Transition(94, 94, 5),
  ], defaultTransition: 6),
  DState([], defaultTransition: -1, accept: rangeSeparator),
  DState([], defaultTransition: -1, accept: characterSetStart),
  DState([
    Transition(45, 45, 7),
    Transition(48, 48, 8),
    Transition(91, 91, 9),
    Transition(92, 92, 10),
    Transition(93, 93, 11),
    Transition(94, 94, 12),
    Transition(102, 102, 13),
    Transition(110, 110, 14),
    Transition(114, 114, 15),
    Transition(116, 116, 16),
    Transition(117, 117, 17),
    Transition(118, 118, 18),
  ], defaultTransition: -1, accept: _unrecognizedEscape),
  DState([], defaultTransition: -1, accept: characterSetEnd),
  DState([], defaultTransition: -1, accept: negation),
  DState([], defaultTransition: -1, accept: literal),
  DState([], defaultTransition: -1, accept: _characterSetEscapes),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([], defaultTransition: -1, accept: _sharedContextEscapes),
  DState([], defaultTransition: -1, accept: _sharedContextEscapes),
  DState([], defaultTransition: -1, accept: _sharedContextEscapes),
  DState([], defaultTransition: -1, accept: _characterSetEscapes),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([
    Transition(123, 123, 19),
  ], defaultTransition: -1),
  DState([], defaultTransition: -1, accept: _controlCharacterEscape),
  DState([
    Transition(48, 57, 20),
    Transition(65, 70, 21),
    Transition(97, 102, 22),
  ], defaultTransition: -1),
  DState([
    Transition(48, 57, 20),
    Transition(65, 70, 21),
    Transition(97, 102, 22),
    Transition(125, 125, 23),
  ], defaultTransition: -1),
  DState([
    Transition(48, 57, 20),
    Transition(65, 70, 21),
    Transition(97, 102, 22),
    Transition(125, 125, 23),
  ], defaultTransition: -1),
  DState([
    Transition(48, 57, 20),
    Transition(65, 70, 21),
    Transition(97, 102, 22),
    Transition(125, 125, 23),
  ], defaultTransition: -1),
  DState([], defaultTransition: -1, accept: _unicodeEscape),
]);
