import '../../regular_scanner.dart';
import '../../state_machine.dart';

/// This class is used for scanners that are generated at runtime.
///
/// Generally speaking, you should not instantiate this class yourself. Use
/// [Scanner.unambiguous], [Scanner.ambiguous] or [Scanner.nondeterministic]
/// instead.
class StateMachineScanner<T, S extends StateMachine<T>> extends Scanner<T, S> {
  StateMachineScanner(this._stateMachine);

  final S _stateMachine;

  @override
  S stateMachine() => _stateMachine.copy() as S;
}

/// This class is generated by package:regular_scanner_builder.
///
/// Do not instantiate this class yourself. Use [Scanner.unambiguous],
/// [Scanner.ambiguous] or [Scanner.nondeterministic] instead.
class BuiltScanner<T> extends Scanner<T, Dfa<T>> {
  const BuiltScanner(this._states);

  final List<DState<T>> _states;

  @override
  Dfa<T> stateMachine() => Dfa(_states);
}
