builders:
  scanner_builder:
    import: "package:regular_scanner/builder.dart"
    builder_factories: ["scannerBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source
    auto_apply: root_package
