builders:
  scanner_builder:
    import: "package:regular_scanner/builder.dart"
    builder_factories: ["scannerBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: root_package
    runs_before: ["source_gen|combining_builder"]
    applies_builders: ["source_gen|combining_builder"]
