name: regular_scanner
description: A `Scanner` class that matches an input string against multiple regular expressions.
version: 0.1.0
dependencies:
  analyzer: any
  build: any
  source_gen: ^0.9.0
  # Not imported in code; This dependency restricts consumers of this package to
  # a version of `build` that still uses the same `build.yaml` format.
  build_config: ^0.3.0
  charcode: any
  collection: any
  lookaround_iterator: any
  meta: '>= 0.9.0 < 2.0.0'
  logging: any
  quiver: any
  mockito: ^3.0.0-beta+1
dev_dependencies:
  build_runner: '>=0.9.1'
  test: any
