name: regular_scanner
version: 0.1.0
dependencies:
  analyzer: any
  build: any
  source_gen: any
  # Not imported in code; This dependency restricts consumers of this package to
  # a version of `build` that still uses the same `build.yaml` format.
  build_config: ^0.2.6
  charcode: any
  collection: any
  lookaround_iterator: any
  meta: '>= 0.9.0 < 2.0.0'
  logging: any
dev_dependencies:
  build_runner: any
