name: regular_scanner
description: Fast, ambiguity-checked regular expressions, and state machine-based general purpose pattern matching.

version: 0.1.0
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  charcode: any
  collection: any
  meta: '>= 0.9.0 < 2.0.0'
  logging: any
  quiver: any
dev_dependencies:
  build_runner: '^1.0.0'
  mockito: ^3.0.0-beta+1
  pedantic_pschiffmann:
    git:
      https://github.com/pschiffmann/pedantic-pschiffmann.dart
  regular_scanner_builder:
    path: ../regular_scanner_builder
  test: any
