name: regular_scanner
description: A `Scanner` class that matches an input string against multiple regular expressions.
version: 0.1.0
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  charcode: any
  collection: any
  meta: '>= 0.9.0 < 2.0.0'
  logging: any
  quiver: any
dev_dependencies:
  build_runner: '^1.0.0'
  test: any
  mockito: ^3.0.0-beta+1
  regular_scanner_builder:
    path: ../regular_scanner_builder
