name: regular_scanner
description: Fast, ambiguity-checked regular expressions, and state machine-based general purpose pattern matching.

version: 0.1.0
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  charcode: any
  collection: any
  meta: ">= 0.9.0 < 2.0.0"
  logging: any
  quiver: any
dev_dependencies:
  build_runner: "^1.0.0"
  mockito: ^3.0.0-beta+1
  pedantic_pschiffmann:
    git:
      url: https://github.com/pschiffmann/pedantic-pschiffmann.dart
      ref: 97fab6223f4e367ccfade79f998bfc137e2e6131
  test: any

  # Only here to test `example/konami_code.dart`.
  # Run with `webdev serve example`.
  #  build_web_compilers: any
  lookaround_iterator: any
  regular_scanner_builder:
    path: ../regular_scanner_builder
